<?php
return [
	'superadmin' => 'superadmin',
	'admin' => 'admin',
	'user' => 'user',
	'survey' => 'survey',
	'tablestriped' => 'table-striped',
	'CreateIcon' => "<i class='font-12 fas fa-plus'></i>",
	'EditIcon' => "<i class='font-12 fas fa-edit'></i>",
	'TrashIcon' => "<i class='font-12 fas fa-trash'></i>",
	'AddDataIcon' => "<i class='font-12 fas fa-plus-square'></i>",
	'Signature' => "<i class='font-12 fa-solid fa-file-signature'></i>",
	'Backpageicon' => "<i class='font-12 fa-solid fa-backward-step'></i>",
	'NoImage' => "<i class='fa-solid fa-image fa-xl'></i>",
	'info-circle' => "<i class='fa-solid fa-circle-info'></i>",
	'add-icon' => "<i class='fa-solid fa-circle-plus fa-xl ' style='color:#063240;font-size:2rem;'></i>",
	'setting-icon' => "<i class='fa-solid fa-gear fa-xl' style='color: #cd7b0a; font-size:2rem;'></i>",
	'LGPDFICON' => "<i class='font-24 fa-solid fa-file-pdf'></i>",
	'fa-circle-exclamation' => "<i class='fa-solid fa-circle-exclamation'></i>",
	'fastar' => "<i class='fa-solid fa-star'></i>",
	'file-import' => "<i class='fa-solid fa-file-import'></i>",
	'download-icon' => "<i class='fa-solid fa-cloud-arrow-down'></i>",
	'success_create_msg'=>"Data is added successfully.",
	'success_update_msg'=>"Data is updated successfully.",
	'success_delete_msg'=>"Data is deleted successfully.",
	'failure_create_msg'=>"Data not added. Please try again.",
	'data_already_exist'=>"Data is already exist.",
	'failure_catch'=>"Something went wrong",
	'stored.information'=>"Stored information",
	'toaster_success'=>"success",
	'toaster_error'=>"error",
	'button_save'=>"Save",
	'organizations_logos'=>"public/assets/organizations/logos/",
	'nodatafound' => 'No data found.',
	'astric_syb' => '<span class="text-danger font-bold">*</span>',
	'api_version' => 'api/v1',
	'api_token' => '89616bad112871a8f7d8e1753a14948dc186f513840923e59012e1f0d8822976',
	'pickon' => '123',
	'card_body_container' => 'card',
	'custom_btn_primary' => 'btn bg-custom-btn rounded-3',
	'optional_input' => 'optional',
	'optional_input_brackets' => '(optional)',
	'pick_one' => '--Pick one--',
	'action_unsuccessful' => 'Action Unsuccessful: An error occurred while processing your request. Please try again later.',
	'action_failed' => 'Action Failed: The system encountered an issue while processing your request. Please refresh the page and try again.',
	'oops_something_wrong' => 'Oops! Something went wrong. Our team has been notified and is working to fix this issue. Please try again later',
	'unable_to_complete' => 'Unable to Complete Action: Please check your internet connection and try again.',
	'email_sent' => 'Email has been sent successfully',
	'email_not_sent' => 'Email was not sent successfully.',
	'verify_ok' => '<i class="fa-solid fa-circle-check" style="color: #36b413;"></i>',
	'verify_not_ok' => '<i class="fa-solid fa-circle-xmark" style="color: #e30251;"></i>',
	'ifemptydataofdeliverabls' => '<p>No Data Found Create New Click on "+" button</p>',

	'accountableTitle'=>'Client Executive',
	'responsibleTitle'=>'Responsible',
	'sNo'=>'S.No.',
	'assignedBy'=>'Assigned By',
	'priority'=>'Priority',
	'status'=>'Status',
	'laststatus'=>'Last Action',
	'actions'=>'Actions',
	'taskDeliverableTitle'=>'Deliverable Title',
	'deliverable'=>'Deliverable',
	'addedOn'=>'Added on',
	'approvalDate'=>'Approval Date',
	'publicationDate'=>'Due Date',
	'brief'=>'Brief',
	'ContentUpdated'=>'content_updated',
	'CreativeUploaded'=>'creative_updated',
	'CodingCompleted'=>'coding_completed',
	'taskTransferred'=>'task_transferred',
	'InvoiceUpdated'=>'invoice_updated',
	'AssetsUploaded'=>'Assets Uploaded',
	'CreativeContentUploaded'=>'Content & Creative Updated',
	'CampaignTaskUpdated'=>'Campaign task updated',
	'CodingURLUpdated'=>'Coded URL and pageSpeed updated',
	'LPPageUpdated'=>'Landing Page updated',
	'LPPageContent'=>'Landing Page Content updated',
	'LPPageAsset'=>'Landing Page Assets updated',
	'LPPageURL'=>'Landing Page URL updated',
	'betweendates'=>'Between Dates',
	'project'=>'Project',
	'button_go'=>'Go',
	'dpd'=>'DPD',
	'priority'=>'Priority',
	'defaultmytaskstatus'=>'not_started,started,in_review,rework,approved,scheduled',

	'icons' => [
        'edit' => 'text-warning fas fa-edit',
        'delete' => 'text-danger fas fa-trash',
        'link' => 'text-info fas fa-link',
		'unit_configuration'=>'text-success fas fa-building',
		'multiple_imges'=>'text-primary fas fa-images',
		'info'=>'text-info fas fa-info-circle',

    ],

];
